networks:
  docker-net:
    name: ${COMPOSE_NET_NAME}-net
    # driver: bridge
    # attachable: true
    external: true

services:
  ruoyivue-admin:
    image: docker.live168.xyz/ruoyi-admin:${ADMIN_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-admin
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    volumes:
      - ${ADMIN_CFG_PATH}/application-admin-prod.yml:/app/application-prod.yml
      - ${ADMIN_LOGS_PATH}/:/app/logs/
    ports:
      - ${ADMIN_PORT}:9527 # 本机端口 → 容器端口
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - docker-net

  ruoyivue-app:
    image: docker.live168.xyz/ruoyi-api:${APP_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-app
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    volumes:
      - ${APP_CFG_PATH}/application-app-prod.yml:/app/application-prod.yml
      - ${APP_LOGS_PATH}/:/app/logs/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - ${APP_PORT}:9528 # 本机端口 → 容器端口
    networks:
      - docker-net
