
# 在任意目录下执行，格式化当前目录及子目录 .env 后缀文件

format-envs:
	chmod +x format-envs.sh
	./format-envs.sh

# 清理 DS_Store 文件
# 在任意目录下执行，清理当前目录及子目录
clean:
	find . -name ".DS_Store" -type f -print -delete

# 格式化sh文件
shfmt:
	shfmt -w .