networks:
  docker-net:
    name: ${COMPOSE_NET_NAME}-net
    # driver: bridge
    # attachable: true
    external: true

services:
  # Redis - 内存数据库
  ruoyi-vue-redis:
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    image: redis:${REDIS_VERSION}
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ${REDIS_DATA_PATH}:/data
      - ${REDIS_LOGS_PATH}:/var/log/redis
    command: >
      sh -c "redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - docker-net

  # MySQL 关系型数据库 - 核心数据存储
  ruoyi-vue-mysql:
    image: mysql:${MYSQL_VERSION} # 官方MySQL镜像
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_INITDB}
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
      - ${MYSQL_LOGS_PATH}:/var/log/mysql
      - ${MYSQL_INIT_SCRIPT}:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --sql-mode=NO_ENGINE_SUBSTITUTION
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - docker-net
