# 定义网络配置
networks:
  # 基础网络使用 bridge 驱动，用于容器间通信
  docker-net:
    name: ${COMPOSE_NET_NAME}-net # 实际引用的 Docker 网络名
    # driver: bridge # 使用 Docker 默认的 bridge 网络驱动
    # attachable: true # 允许其他容器附加到此网络
    external: true

services:
  nginx-main-admin:
    image: nginx:${NGINX_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-nginx-admin
    restart: unless-stopped
    environment:
      TZ: ${TZ} # 时区设置，从环境变量获取
    volumes:
      - ${NGINX_CFG_PATH}/app/default.conf:/etc/nginx/nginx.conf
      - ${NGINX_DATA_PATH}/admin/logs:/var/log/nginx
      - ${NGINX_CFG_PATH}/proxy/admin.cnf:/etc/nginx/proxy.cnf # 添加额外的配置文件
      - ${WEBDIR}/admin:/etc/nginx/webdir/ # 添加额外的配置文件
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "60000:80" # 本机端口 → 容器端口
    networks:
      - docker-net

  nginx-mobile:
    image: nginx:${NGINX_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-nginx-mobile
    restart: unless-stopped
    environment:
      TZ: ${TZ} # 时区设置，从环境变量获取
    volumes:
      - ${NGINX_CFG_PATH}/app/default.conf:/etc/nginx/nginx.conf
      - ${NGINX_DATA_PATH}/mobile/logs:/var/log/nginx
      - ${NGINX_CFG_PATH}/proxy/app.cnf:/etc/nginx/proxy.cnf # 添加额外的配置文件
      - ${WEBDIR}/1037_Exch_Sgpmx_Test:/etc/nginx/webdir/ # 添加额外的配置文件
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "61000:80" # 本机端口 → 容器端口
    networks:
      - docker-net
